config:
  pumlmi_demo_app-infra:environment: production
  pumlmi_demo_app-infra:location: eastasia
  pumlmi_demo_app-infra:dbName: myappdb
  pumlmi_demo_app-infra:dbUser: myappuser
  pumlmi_demo_app-infra:backendImage: temp
  pumlmi_demo_app-infra:acrLoginServer: temp
